namespace: devblog-ns

replicaCount: 2

image:
  repository: k8s.gcr.io/ingress-nginx/controller
  tag: "v1.2.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - paths:
        - path: /blog(/|$)(.*)
          pathType: Prefix
          serviceName: blog-service
          servicePort: 80

resources: { }