{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-service.fullname" .}}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "user-service.name" .}}
    chart: {{ include "user-service.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    codeVersion: {{ .Values.codeVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "user-service.name" . }}
      release: {{ .Release.Name }}
      codeVersion: {{ .Values.codeVersion }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ include "user-service.name" . }}
        release: {{ .Release.Name }}
        codeVersion: {{ .Values.codeVersion }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
      nodeSelector: {{ toYaml .Values.nodeSelector | indent 0 }}
      tolerations: {{ toYaml .Values.tolerations | indent 0 }}
      affinity: {{ toYaml .Values.affinity | indent 0 }}
{{- end }}
