apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "user-service.name" . }}
    chart: {{ include "user-service.chart" . }}
    release: {{ .Release.Name}}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ include "user-service.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}