apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-ingress.fullname" . }}
  labels:
    app: {{ include "nginx-ingress.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "nginx-ingress.name" . }}